#!/usr/bin/env bash
#
# build.sh — compile with SwiftPM, assemble the macOS .app bundle, codesign.
#
# Usage:  ./build.sh [debug|release]
#
# Driven by the Makefile. NO Xcode IDE, NO xcodebuild — `swift build` does the
# compile, this script does the bundling and signing. Xcode is only a toolchain
# provider (swift / codesign / notarytool / stapler).
#
# Environment:
#   SIGN_IDENTITY  codesign identity. Defaults to ad-hoc ("-"), which is all
#                  running it on your own machine needs: the app has no iCloud
#                  or other entitlement a provisioning profile would have to
#                  grant.
#   VERSION        CFBundleShortVersionString to stamp (default 0.0.0).
#
set -euo pipefail

CONFIG="${1:-debug}"
PACKAGE_PATH="Packages/StarterKit"
# The SwiftPM executable target and the .app it ends up inside are named
# differently: the target says it is the Mac app, the bundle is what you see
# in the Dock.
EXECUTABLE_NAME="StarterMac"
APP_NAME="Starter"
BUILD_DIR="build"
APP="$BUILD_DIR/$APP_NAME.app"
SIGN_IDENTITY="${SIGN_IDENTITY:--}"
VERSION="${VERSION:-0.0.0}"
ENTITLEMENTS="StarterMac/StarterMac.entitlements"
INFO_PLIST_SRC="Resources/Info.plist"

# Build number: monotonic-ish from the date so re-signs differ. Falls back to 1.
BUILD_NUMBER="$(date +%Y%m%d%H%M 2>/dev/null || echo 1)"

# Pinned: build exactly what Package.resolved says, and fail rather than
# quietly re-resolving to something newer.
echo "→ swift build -c $CONFIG ($PACKAGE_PATH)"
swift build --package-path "$PACKAGE_PATH" -c "$CONFIG" --force-resolved-versions

BIN_PATH="$(swift build --package-path "$PACKAGE_PATH" -c "$CONFIG" --force-resolved-versions --show-bin-path)"
EXECUTABLE="$BIN_PATH/$EXECUTABLE_NAME"
if [ ! -x "$EXECUTABLE" ]; then
	echo "✗ executable not found at $EXECUTABLE" >&2
	exit 1
fi

# ---------------------------------------------------------------------------
# Assemble the bundle
# ---------------------------------------------------------------------------
echo "→ assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$EXECUTABLE" "$APP/Contents/MacOS/$EXECUTABLE_NAME"

sed -e "s/__SHORT_VERSION__/$VERSION/g" \
    -e "s/__BUILD_VERSION__/$BUILD_NUMBER/g" \
    "$INFO_PLIST_SRC" > "$APP/Contents/Info.plist"

# PkgInfo — classic 8-byte file some macOS code paths still look for.
printf 'APPL????' > "$APP/Contents/PkgInfo"

# SwiftPM resource bundles — if any dependency ships a `*.bundle`, copy it
# into Contents/Resources so the app finds it once moved away from `.build`.
for bundle in "$BIN_PATH"/*.bundle; do
	if [ -e "$bundle" ]; then
		cp -R "$bundle" "$APP/Contents/Resources/"
		echo "  bundled $(basename "$bundle")"
	fi
done

# App icon (optional — generated by `make icon`).
if [ -f "$BUILD_DIR/AppIcon.icns" ]; then
	cp "$BUILD_DIR/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
else
	echo "  (no $BUILD_DIR/AppIcon.icns — run 'make icon'; bundling without one)"
fi

# ---------------------------------------------------------------------------
# Codesign — ad-hoc by default, so `make run` works on a machine with no
# certs at all. The sandbox entitlement needs a signature to take effect;
# ad-hoc is enough.
# ---------------------------------------------------------------------------
echo "→ codesign ($SIGN_IDENTITY)"
codesign --force --sign "$SIGN_IDENTITY" --entitlements "$ENTITLEMENTS" "$APP"

codesign --verify --verbose=1 "$APP"
echo "✓ built $APP"
